server:
  port: 8081
Mybatis:
  type-aliases-package: com.term.api.model
  config-location: classpath:Mybatis/mybatis-config.xml
  mapper-locations: classpath:Mybatis/mapper/*.xml

spring:
  application:
    name: Springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#Eureka的配置，配置注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/,http://eureka2:8003/eureka/,http://eureka3:8004/eureka/

  instance:
    # 用于修改eureka上的描述信息
    instance-id: springcloud-DeptServiceProvider-8081

info:
  app.name: DeptServiceProvider
  company.name: Term
